### ISSUE TITLE
[8pts] Cart Functionality

### ISSUE THREAD

**Issue by Megagig** [Megagig/shopmaster#7]
- Products should be added to cart 
- Products should also be removed from Cart
- Design the cartPage with Tailwind css
- Implement the following components in the cart page.
- Wrap the App component with the CartProvider in src/index.js.

1.  CartCard
2. CartList
3. EmptyCart

- Make sure to properly design all the components with Tailwind CSS
- Remember to do all this using ContextAPI

**Comment by Divinechi** [comment]
Thank you
